name: Deploy Packages and App

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: package-lock.json,app/package-lock.json,packages/package-lock.json

      - name: Install Main Dependencies
        run: |
          npm ci

      - name: Install App Dependencies
        run: |
          cd app
          npm ci

      - name: Install Node Libraries
        run: |
          cd packages
          npm ci

      # - name: Verify Dependencies
      #   run: npm run verify-dependencies -- --ci true

      # - name: Lint
      #   run: npm run lint

      # - name: Run unit tests
      #   run: npm run test:unit

      # - name: Run integration tests
      #   run: npm run test:integration

      # - name: Run e2e tests
      #   run: npm run test:e2e

      # - name: Cover
      #   run: npm run coverage

      - name: Publish libraries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run build

          ls -la app/dist/devcrate/ngx-dc-data-sources
          ls -la app/dist/devcrate/ngx-dc-styles

          ls -la app/dist/devcrate
          ls -la packages/dist
          ls -la packages/dist/utils
          ls -la packages/dist/playwright
          ls -la packages/dist/eslint-config

          git config user.name "DevCrate"
          git config user.email "danielmhair@gmail.com"


          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm run publish
          rm ~/.npmrc

      - name: Deploy App to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "DevCrate"
          git config user.email "danielmhair@gmail.com"
          cd app
          npm run deploy
