name: Deploy Packages and App

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish to npm'
        type: boolean
        required: true
        default: false
      deployment_type:
        description: 'What to deploy'
        type: choice
        required: true
        default: 'all'
        options:
          - all
          - app-only
          - packages-only

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: package-lock.json,app/package-lock.json,packages/package-lock.json

      - name: Setup git and npmrc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "DevCrate"
          git config user.email "danielmhair@gmail.com"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install All Dependencies
        run: |
          npm ci
          cd app && npm ci
          cd ../packages && npm ci

      - name: Build Libraries
        run: |
          npm run build

      - name: Force Publish
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.force_publish == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run publish -- --force-publish

      - name: Publish
        if: github.event_name == 'push' || github.event.inputs.force_publish == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run publish

      - name: Deploy App to Github Pages
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.deployment_type == 'all' || github.event.inputs.deployment_type == 'app-only'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd app
          npm run deploy
